version: '3.9'
services:
  api:
    image: nikolajhm7/bakerydbimage:api
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - mssql
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "abc123AB"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_SA_PASSWORD: "abc123AB"
      MSSQL_DATABASE: "BakeryDB"
    ports:
      - "1433:1433"